### ISSUE TITLE
Remove toNat from LLVM semantics

### ISSUE THREAD

**Issue by tobiasgrosser** [opencompl/lean-mlir#694]
Several LLVM functions use toNat, while they can use a bit-vector level comparison which would allow them to be bitblasted.

We should transform this code:

```lean
@[simp_llvm]
def lshr? {n} (op1 : BitVec n) (op2 : BitVec n) : IntW n :=
  let bits := op2.toNat
  if bits >= n then .none
  else pure (op1 >>> op2)
```

into 

```lean
@[simp_llvm]
def lshr? {n} (op1 : BitVec n) (op2 : BitVec n) : IntW n :=
  let bits := op2
  if bits >= n then .none
  else pure (op1 >>> op2)
```

and while at it, clean it up to sth like:

```lean
@[simp_llvm]
def lshr? {n} (op1 : BitVec n) (op2 : BitVec n) : IntW n :=
  if op2 >= n then
    none
  else
    pure (op1 >>> op2)
```

**Comment by lfrenot** [comment]
Using BitVec.ofNat is fine, right?

**Comment by tobiasgrosser** [comment]
In which way? Why do you need it?

**Comment by lfrenot** [comment]
When you write `op2 >= n` in `lshr`, you're comparing a BitVec with a Nat
I don't think this works properly
But I may be wrong

**Comment by tobiasgrosser** [comment]
This should work in `bv_decide`.

**Comment by tobiasgrosser** [comment]
What is your concern?

**Comment by lfrenot** [comment]
> This should work in `bv_decide`.

oh okay, then there is no issue indeed
I'll do that and open a PR
