### ISSUE TITLE
llvm: add `or disjoint` support

### ISSUE THREAD

**Issue by tobiasgrosser** [opencompl/lean-mlir#822]
There are three lemmas which require `or disjoint` support in our LLVM semantics. For details see: https://llvm.org/docs/LangRef.html#or-instruction.

This will fix programs in:

- subhofhnegatible
- xor.ll
- gbinophofhdisplacedhshifts

**Comment by lfrenot** [comment]
Made a PR for the MLIR side: https://github.com/llvm/llvm-project/pull/115855

**Comment by lfrenot** [comment]
Made a PR for the xDSL side: https://github.com/xdslproject/xdsl/pull/3428
