### ISSUE TITLE
llvm: test_two_argument_ranges_thm

### ISSUE THREAD

**Issue by tobiasgrosser** [opencompl/lean-mlir#831]
This theorem is not filtered even with the latest patches.

**Comment by tobiasgrosser** [comment]
I merged https://github.com/opencompl/lean-mlir/commit/e3f3f4554ff137e4389fbfab6ebfffa15e9a45a8, but this patch does not seem to be sufficient. @lfrenot, can you investigate.

**Comment by lfrenot** [comment]
I found it, the issue was something completely different than what I thought, sorry
I'm making a patch right now, also the PR I made yesterday should be reversed
